module Net
  module SNMP
    module Constants
      MAX_OID_LEN = 128

      # Return values of various send functions
      STAT_SUCCESS        = 0
      STAT_ERROR          = 1
      STAT_TIMEOUT        = 2

      # SNMP versions
      SNMP_VERSION_1 = 0
      SNMP_VERSION_2c = 1
      SNMP_VERSION_3 = 3

      # PDU variable types
      ASN_BOOLEAN         = 0x01
      ASN_INTEGER         = 0x02
      ASN_BIT_STR         = 0x03
      ASN_OCTET_STR       = 0x04
      ASN_NULL            = 0x05
      ASN_OBJECT_ID       = 0x06
      ASN_SEQUENCE        = 0x10
      ASN_SET             = 0x11

      ASN_UNIVERSAL       = 0x00
      ASN_APPLICATION     = 0x40
      ASN_CONTEXT         = 0x80
      ASN_PRIVATE         = 0xC0

      ASN_PRIMITIVE       = 0x00
      ASN_CONSTRUCTOR     = 0x20

      ASN_LONG_LEN        = 0x80
      ASN_EXTENSION_ID    = 0x1F
      ASN_BIT8            = 0x80


      ASN_IPADDRESS   = (ASN_APPLICATION | 0)
      ASN_COUNTER     = (ASN_APPLICATION | 1)
      ASN_GAUGE       = (ASN_APPLICATION | 2)
      ASN_UNSIGNED    = (ASN_APPLICATION | 2)   # RFC 1902 - same as GAUGE
      ASN_TIMETICKS   = (ASN_APPLICATION | 3)
      ASN_OPAQUE      = (ASN_APPLICATION | 4)
      ASN_NSAP        = (ASN_APPLICATION | 5)  # historic - don't use
      ASN_COUNTER64   = (ASN_APPLICATION | 6)
      ASN_UINTEGER    = (ASN_APPLICATION | 7)   # historic - don't use

      # Exception values for SNMPv2 and SNMPv3
      SNMP_NOSUCHOBJECT   = (ASN_CONTEXT | ASN_PRIMITIVE | 0x0)
      SNMP_NOSUCHINSTANCE = (ASN_CONTEXT | ASN_PRIMITIVE | 0x1)
      SNMP_ENDOFMIBVIEW      = (ASN_CONTEXT | ASN_PRIMITIVE | 0x2)


      # PDU types
      SNMP_MSG_GET        = (ASN_CONTEXT | ASN_CONSTRUCTOR | 0x0)
      SNMP_MSG_GETNEXT    = (ASN_CONTEXT | ASN_CONSTRUCTOR | 0x1) 
      SNMP_MSG_RESPONSE   = (ASN_CONTEXT | ASN_CONSTRUCTOR | 0x2) 
      SNMP_MSG_SET        = (ASN_CONTEXT | ASN_CONSTRUCTOR | 0x3)
      SNMP_MSG_TRAP       = (ASN_CONTEXT | ASN_CONSTRUCTOR | 0x4)
      SNMP_MSG_GETBULK    = (ASN_CONTEXT | ASN_CONSTRUCTOR | 0x5)
      SNMP_MSG_INFORM     = (ASN_CONTEXT | ASN_CONSTRUCTOR | 0x6)
      SNMP_MSG_TRAP2      = (ASN_CONTEXT | ASN_CONSTRUCTOR | 0x7)
      SNMP_MSG_REPORT     = (ASN_CONTEXT | ASN_CONSTRUCTOR | 0x8)
      

      # Callback status codes
      NETSNMP_CALLBACK_OP_RECEIVED_MESSAGE  =  1
      NETSNMP_CALLBACK_OP_TIMED_OUT         =  2
      NETSNMP_CALLBACK_OP_SEND_FAILED       =  3
      NETSNMP_CALLBACK_OP_CONNECT           =  4
      NETSNMP_CALLBACK_OP_DISCONNECT        =  5
      

      # Error codes (the value of the field error-status in PDUs)

      # in SNMPv1, SNMPsec, SNMPv2p, SNMPv2c, SNMPv2u, SNMPv2*, and SNMPv3 PDUs
      SNMP_ERR_NOERROR               = (0)     # XXX  Used only for PDUs?
      SNMP_ERR_TOOBIG                = (1)
      SNMP_ERR_NOSUCHNAME            = (2)
      SNMP_ERR_BADVALUE              = (3)
      SNMP_ERR_READONLY              = (4)
      SNMP_ERR_GENERR                = (5)

      # in SNMPv2p, SNMPv2c, SNMPv2u, SNMPv2*, and SNMPv3 PDUs
      SNMP_ERR_NOACCESS               = (6)
      SNMP_ERR_WRONGTYPE              = (7)
      SNMP_ERR_WRONGLENGTH            = (8)
      SNMP_ERR_WRONGENCODING          = (9)
      SNMP_ERR_WRONGVALUE             = (10)
      SNMP_ERR_NOCREATION             = (11)
      SNMP_ERR_INCONSISTENTVALUE      = (12)
      SNMP_ERR_RESOURCEUNAVAILABLE    = (13)
      SNMP_ERR_COMMITFAILED           = (14)
      SNMP_ERR_UNDOFAILED             = (15)
      SNMP_ERR_AUTHORIZATIONERROR     = (16)
      SNMP_ERR_NOTWRITABLE            = (17)

      # in SNMPv2c, SNMPv2u, SNMPv2*, and SNMPv3 PDUs
      SNMP_ERR_INCONSISTENTNAME       = (18)


      # SNMP Errors
      SNMPERR_SUCCESS = (0)
      SNMPERR_GENERR = (-1)
      SNMPERR_BAD_LOCPORT = (-2)
      SNMPERR_BAD_ADDRESS = (-3)
      SNMPERR_BAD_SESSION = (-4)
      SNMPERR_TOO_LONG = (-5)
      SNMPERR_NO_SOCKET = (-6)
      SNMPERR_V2_IN_V1 = (-7)
      SNMPERR_V1_IN_V2 = (-8)
      SNMPERR_BAD_REPEATERS = (-9)
      SNMPERR_BAD_REPETITIONS = (-10)
      SNMPERR_BAD_ASN1_BUILD = (-11)
      SNMPERR_BAD_SENDTO = (-12)
      SNMPERR_BAD_PARSE = (-13)
      SNMPERR_BAD_VERSION = (-14)
      SNMPERR_BAD_SRC_PARTY = (-15)
      SNMPERR_BAD_DST_PARTY = (-16)
      SNMPERR_BAD_CONTEXT = (-17)
      SNMPERR_BAD_COMMUNITY = (-18)
      SNMPERR_NOAUTH_DESPRIV = (-19)
      SNMPERR_BAD_ACL = (-20)
      SNMPERR_BAD_PARTY = (-21)
      SNMPERR_ABORT = (-22)
      SNMPERR_UNKNOWN_PDU = (-23)
      SNMPERR_TIMEOUT = (-24)
      SNMPERR_BAD_RECVFROM = (-25)
      SNMPERR_BAD_ENG_ID = (-26)
      SNMPERR_BAD_SEC_NAME = (-27)
      SNMPERR_BAD_SEC_LEVEL = (-28)
      SNMPERR_ASN_PARSE_ERR = (-29)
      SNMPERR_UNKNOWN_SEC_MODEL = (-30)
      SNMPERR_INVALID_MSG = (-31)
      SNMPERR_UNKNOWN_ENG_ID = (-32)
      SNMPERR_UNKNOWN_USER_NAME = (-33)
      SNMPERR_UNSUPPORTED_SEC_LEVEL = (-34)
      SNMPERR_AUTHENTICATION_FAILURE = (-35)
      SNMPERR_NOT_IN_TIME_WINDOW = (-36)
      SNMPERR_DECRYPTION_ERR = (-37)
      SNMPERR_SC_GENERAL_FAILURE = (-38)
      SNMPERR_SC_NOT_CONFIGURED = (-39)
      SNMPERR_KT_NOT_AVAILABLE = (-40)
      SNMPERR_UNKNOWN_REPORT = (-41)
      SNMPERR_USM_GENERICERROR = (-42)
      SNMPERR_USM_UNKNOWNSECURITYNAME = (-43)
      SNMPERR_USM_UNSUPPORTEDSECURITYLEVEL = (-44)
      SNMPERR_USM_ENCRYPTIONERROR = (-45)
      SNMPERR_USM_AUTHENTICATIONFAILURE = (-46)
      SNMPERR_USM_PARSEERROR = (-47)
      SNMPERR_USM_UNKNOWNENGINEID = (-48)
      SNMPERR_USM_NOTINTIMEWINDOW = (-49)
      SNMPERR_USM_DECRYPTIONERROR = (-50)
      SNMPERR_NOMIB = (-51)
      SNMPERR_RANGE = (-52)
      SNMPERR_MAX_SUBID = (-53)
      SNMPERR_BAD_SUBID = (-54)
      SNMPERR_LONG_OID = (-55)
      SNMPERR_BAD_NAME = (-56)
      SNMPERR_VALUE = (-57)
      SNMPERR_UNKNOWN_OBJID = (-58)
      SNMPERR_NULL_PDU = (-59)
      SNMPERR_NO_VARS = (-60)
      SNMPERR_VAR_TYPE = (-61)
      SNMPERR_MALLOC = (-62)
      SNMPERR_KRB5 = (-63)
      SNMPERR_PROTOCOL = (-64)
      SNMPERR_OID_NONINCREASING = (-65)
      SNMPERR_MAX = (-65)



      USM_AUTH_KU_LEN = 32
      USM_PRIV_KU_LEN = 32

      # SNMPv3 Security Levels
      SNMP_SEC_LEVEL_NOAUTH = 1
      SNMP_SEC_LEVEL_AUTHNOPRIV = 2
      SNMP_SEC_LEVEL_AUTHPRIV = 3

      SNMP_DEFAULT_COMMUNITY_LEN = 0
      SNMP_DEFAULT_RETRIES = -1
      SNMP_DEFAULT_TIMEOUT = -1
      SNMP_DEFAULT_REMPORT = 0
      SNMP_DEFAULT_REQID = -1
      SNMP_DEFAULT_MSGID = -1
      SNMP_DEFAULT_ERRSTAT = -1
      SNMP_DEFAULT_ERRINDEX = -1
      SNMP_DEFAULT_ADDRESS = 0
      SNMP_DEFAULT_ENTERPRISE_LENGTH = 0
      SNMP_DEFAULT_TIME = 0
      SNMP_DEFAULT_VERSION = -1
      SNMP_DEFAULT_SECMODEL = -1
      SNMP_DEFAULT_CONTEXT = 

      SNMP_MAX_MSG_SIZE = 1472
      SNMP_MAX_MSG_V3_HDRS = (4+3+4+7+7+3+7+16)
      SNMP_MAX_ENG_SIZE = 32
      SNMP_MAX_SEC_NAME_SIZE = 256
      SNMP_MAX_CONTEXT_SIZE = 256
      SNMP_SEC_PARAM_BUF_SIZE = 256
      SNMPV3_IGNORE_UNAUTH_REPORTS = 0
      SNMP_SESS_NONAUTHORITATIVE = 0
      SNMP_SESS_AUTHORITATIVE = 1
      SNMP_SESS_UNKNOWNAUTH = 2
      REPORT_STATS_LEN = 9
      REPORT_snmpUnknownSecurityModels_NUM = 1
      REPORT_snmpInvalidMsgs_NUM = 2
      REPORT_usmStatsUnsupportedSecLevels_NUM = 1
      REPORT_usmStatsNotInTimeWindows_NUM = 2
      REPORT_usmStatsUnknownUserNames_NUM = 3
      REPORT_usmStatsUnknownEngineIDs_NUM = 4
      REPORT_usmStatsWrongDigests_NUM = 5
      REPORT_usmStatsDecryptionErrors_NUM = 6
      SNMP_DETAIL_SIZE = 512
      SNMP_FLAGS_RESP_CALLBACK = 0x400
      SNMP_FLAGS_USER_CREATED = 0x200
      SNMP_FLAGS_DONT_PROBE = 0x100
      SNMP_FLAGS_STREAM_SOCKET = 0x80
      SNMP_FLAGS_LISTENING = 0x40
      SNMP_FLAGS_SUBSESSION = 0x20
      SNMP_FLAGS_STRIKE2 = 0x02
      SNMP_FLAGS_STRIKE1 = 0x01


      STAT_SNMPUNKNOWNSECURITYMODELS = 0
      STAT_SNMPINVALIDMSGS = 1
      STAT_SNMPUNKNOWNPDUHANDLERS = 2
      STAT_MPD_STATS_START = 0
      STAT_MPD_STATS_END = 2
      STAT_USMSTATSUNSUPPORTEDSECLEVELS = 3
      STAT_USMSTATSNOTINTIMEWINDOWS = 4
      STAT_USMSTATSUNKNOWNUSERNAMES = 5
      STAT_USMSTATSUNKNOWNENGINEIDS = 6
      STAT_USMSTATSWRONGDIGESTS = 7
      STAT_USMSTATSDECRYPTIONERRORS = 8
      STAT_USM_STATS_START = 3
      STAT_USM_STATS_END = 8
      STAT_SNMPINPKTS = 9
      STAT_SNMPOUTPKTS = 10
      STAT_SNMPINBADVERSIONS = 11
      STAT_SNMPINBADCOMMUNITYNAMES = 12
      STAT_SNMPINBADCOMMUNITYUSES = 13
      STAT_SNMPINASNPARSEERRS = 14
      STAT_SNMPINTOOBIGS = 16
      STAT_SNMPINNOSUCHNAMES = 17
      STAT_SNMPINBADVALUES = 18
      STAT_SNMPINREADONLYS = 19
      STAT_SNMPINGENERRS = 20
      STAT_SNMPINTOTALREQVARS = 21
      STAT_SNMPINTOTALSETVARS = 22
      STAT_SNMPINGETREQUESTS = 23
      STAT_SNMPINGETNEXTS = 24
      STAT_SNMPINSETREQUESTS = 25
      STAT_SNMPINGETRESPONSES = 26
      STAT_SNMPINTRAPS = 27
      STAT_SNMPOUTTOOBIGS = 28
      STAT_SNMPOUTNOSUCHNAMES = 29
      STAT_SNMPOUTBADVALUES = 30
      STAT_SNMPOUTGENERRS = 32
      STAT_SNMPOUTGETREQUESTS = 33
      STAT_SNMPOUTGETNEXTS = 34
      STAT_SNMPOUTSETREQUESTS = 35
      STAT_SNMPOUTGETRESPONSES = 36
      STAT_SNMPOUTTRAPS = 37
      STAT_SNMPSILENTDROPS = 39
      STAT_SNMPPROXYDROPS = 40
      STAT_SNMP_STATS_START = 9
      STAT_SNMP_STATS_END = 40
      STAT_SNMPUNAVAILABLECONTEXTS = 41
      STAT_SNMPUNKNOWNCONTEXTS = 42
      STAT_TARGET_STATS_START = 41
      STAT_TARGET_STATS_END = 42
      MAX_STATS = 43
      PARSE_PACKET = 0
      DUMP_PACKET = 1
      MAX_SUBID = 0xFFFFFFFF
      MIN_OID_LEN = 2

      MAX_NAME_LEN = 128
      
    end
  end
end
